extra_hosts now works on docker
ansible/ansible-container pull request #805
Opened 2017-11-25 15:27 UTC by marcosdiez

##### ISSUE TYPE
 - Bugfix Pull Request

##### SUMMARY
Ansible-Container was ignoring the `extra_hosts` setting from `container.yml`.

Fortunatelly it was an easy fix: all I had to do was to pass this setting inside of 

`container/docker/engine.py generate_orchestration_playbook()`

So now all my containers have `extra_hosts` !

2017-11-30 13:45 UTC, chouseknecht commented
@marcosdiez 

Thanks for the contribution! We appreciate you taking the time to work on this. 

On the surface, this doesn't feel right to me. We don't want to enumerate every Docker compose directive during orchestration. At one point there was a _whitelist_ of supported directives, which existed because we were limiting directives to those that translated easily to K8s.

I'll research this a bit more, and see if I can provide a better response. 

Thanks for your patience!

2017-11-30 14:28 UTC, marcosdiez commented
Hi @chouseknecht 

extra_hosts is documented.
That's why I added...

https://docs.ansible.com/ansible-container/container_yml/reference.html#services

https://docs.ansible.com/ansible-container/container_yml/reference.html#extra-hosts

2017-11-30 14:33 UTC, marcosdiez commented
Now.... it's funny that you don't plan to implement all docker-compose feature.

In my current project, I have the following setup and I am pretty happy with it:

- all containers are made using ansible containers
- after they are done, I run a python script that converts `container.yml` into `docker-compose.yml`

that guarantees that my developers and my cloud machines run exactly the same configuration.

I planned, after finishing this project, to push back the code to convert `container.yml` do `docker-compose.yml`  
(sorry, waiting one minute to launching containers is too much for us)

but now that you are telling me that, by design you want to to offer as little settings as possible, I am kind of unsure if I picked the right tool for the job.

2017-12-01 11:58 UTC, chouseknecht commented on container/docker/engine.py
> +            if 'extra_hosts' in service:
Add `extra_hosts` to COMPOSE_WHITELIST above, and this should just work.

2017-12-01 12:00 UTC, chouseknecht requested changes
See comment

2017-12-01 12:03 UTC, chouseknecht commented
@marcosdiez 

I think your point regarding `waiting one minute to launching containers is too much for us` is completely valid. Rather than forcing the docker engine to orchestrate via playbook, I wonder if we should go back to orchestrating via the `docker` Python module.

2017-12-01 12:32 UTC, mdiez-modus commented
Sorry, @chouseknecht 
now I understand what you meant.

I thought there was some documentation about which commands you guys plan to implement because because the aim of the tool would be to be a common denominator between docker and k8s.

About `waiting one minute to launching containers is too much for us`, well... less waiting is better than more waiting :)

2017-12-01 13:51 UTC, chouseknecht approved these changes

2017-12-01 13:51 UTC, merged